services:
  recipe_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./recipebot:/app/recipebot
    command: python -m recipebot.drivers.main
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    networks:
      - recipe_default

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_recipe_bot_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - recipe_default

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_recipe_bot_data:/var/lib/grafana
    ports:
      - "3050:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - recipe_default
    depends_on:
      - prometheus

networks:
  recipe_default:

volumes:
  prometheus_recipe_bot_data:
  grafana_recipe_bot_data:
