services:
  recipe_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./recipebot:/app/recipebot
    command: python -m recipebot.drivers.main
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    networks:
      - recipe_default
    depends_on:
      postgres_recipe:
        condition: service_healthy

networks:
  recipe_default:

volumes:
  pg_recipe_data:
  pgadmin_recipe_data:
